version: '2'

services:
  lac:
    image: sg-lac:5.1.00
    ports: 
      - 8081:8080
    environment:
      CATALINA_OPTS: "-javaagent:/home/dd-java-agent.jar -Ddd.service.name=lac -Ddd.agent.host=172.17.0.1 -Ddd.agent.port=8126 --add-modules java.xml.bind"

    volumes:
      - ./data/CALiveAPICreator.repository:/home/tomcat/CALiveAPICreator.repository
      - ./data/databases:/usr/local/CALiveAPICreator/databases 
    network_mode: bridge